HEC.WAT.ForecastProcessor.FIRO_WFP_Alternative=EFP
EfpWatPlugin.Description.label=A plugin to compute forecast metrics from ensemble forecast timeseries data
EfpWatPlugin.Name.label=WAT Ensemble Forecast Processor (EFP)
EfpWatPlugin.ShortName.label=EFP
EfpWatPlugin.label=WAT EFP Plugin Alternative
EfpWatPlugin.Editor.Title.label=Ensemble Forecast Processor (EFP)
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.Header.Name.label=Data Location Name
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.Header.Parameter.label=Parameter
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.Header.DataLocationType.label=Type
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.Header.UserDefField.label=Field
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.Header.SetField.label=...
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.Button.Add.label=+
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.Button.Delete.label=-
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.Msg.DeleteLocation.label=Delete this location?
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.Msg.DeleteLocation.Title.label=Delete Location?
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.DefaultParameter.label=FLOW
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.DefaultName.label=LOCATION NAME
HEC.WAT.ForecastProcessor.UI.DataLocationPanel.WatMethodLabel.label=Output Stepped Time-series?
Editor.Panel.Tab.Name.label=Editor Panel Tab Name
Editor.Panel.Title.DataLocations.label=EFP Configuration
Editor.Panel.Label.TimeStep.label=Output Timestep
Editor.Panel.TimeStep.Default.label=IR-YEAR
Editor.Panel.Title.Input.label=Input Locations (Forecasts)
Editor.Panel.Title.Output.label=Output Locations (Metrics)